name: Load Testing Pipline

on:
    push:
        branches:
            - master

jobs:
    Load-test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Install node
              uses: actions/setup-node@v4
              with:
                node-version: 16

            - name: Install dependences
              run: npm install

            - name: Install K6
              run: sudo snap install k6

            - name: start app
              run: |
                npm start &
                sleep 5
 
            - name: Run Load Testing
              run: k6 run load-test.js

            - name: Run OWASP ZAP Baseline Scan
              run: |
                docker run --rm -v $(pwd):/zap/wrk:rw -t owasp/zap2docker-stable zap-baseline.py \ -t http://localhost:3000 \ -g gen.conf -r zap-report.html || true

            - name: Upload ZAP Report
              uses: actions/upload-artifact@v4
              with:
                name: zap-security-report
                path: zap-report.html

            
